### ISSUE TITLE
Search Logic - No Filters Selected, No Location Selected

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#24] opened 2017-02-02 16:21 UTC
From Search Page - 
When no filters are selected, the search should return all services (pins) in the DB for the user designated search location.

When no location is designated (location box left empty) the search area should default to zip code 53715 (for MVP-1, this will change to user location for MVP-2 or 3)

Thank you!

**Comment by phillipskevin** [comment] 2017-04-14 22:51
duplicate of #41 .

**Closed by phillipskevin** 2017-04-14 22:51 UTC
